//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.16 at 09:09:46 PM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://vanier.com/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.vanier_com.courses;
